[package]
name = "cagara-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cagara"
path = "src/main.rs"

[dependencies]
cagara-hir.workspace = true
cagara-sql.workspace = true
cagara-lsp.workspace = true
cagara-fmt.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
